---

- hosts: all
  become: true
  tasks:

  - name: update packages cache
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

  - name: install NGINX
    apt:
      name: nginx
      state: latest
    when: ansible_distribution == "Ubuntu"